language: python

python:
  - "3.7"
  - "nightly"

env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - pycodestyle . --max-line-length=119
  - python -m pytest --cov-report html --cov app

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"

notifications:
  email: false

after_success:
- coveralls
