"""empty message

Revision ID: fc4bb3f87c1a
Revises: 245e431f235a
Create Date: 2019-06-02 22:16:36.169262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4bb3f87c1a'
down_revision = '245e431f235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_email'), 'email', ['email'], unique=True)
    op.drop_index('ix_contact_email', table_name='contact')
    op.drop_column('contact', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_contact_email', 'contact', ['email'], unique=1)
    op.drop_index(op.f('ix_email_email'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
