# --- !Ups

create table "contacts" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "user_name" varchar not null,
  "first_name" varchar null,
  "last_name" varchar null ,
);

# --- !Downs

drop table "contacts" if exists;
